added homework-04
LesyaTkachuk/goit-nodejs-homeworks pull request #4
Opened 2020-09-18 17:55 UTC by LesyaTkachuk

2020-09-19 08:55 UTC, odykyi commented on src/corn/token-cleaner.js
> +    setTimeout(main, 24 * 60 * 60 * 1000);
setInterval

2020-09-19 08:56 UTC, odykyi requested changes
comments

2020-09-19 09:25 UTC, LesyaTkachuk commented on src/corn/token-cleaner.js
> +    setTimeout(main, 24 * 60 * 60 * 1000);
Это я исправила и запушила. Надо новый pull request создавать или изменения автоматически сюда подтянутся?

2020-09-21 07:14 UTC, odykyi approved these changes

2020-09-21 07:14 UTC, merged