added homework-06
LesyaTkachuk/goit-nodejs-homeworks pull request #6
Opened 2020-10-05 19:15 UTC by LesyaTkachuk

2020-10-08 15:00 UTC, odykyi commented on src/helpers/nodmailer.js
> +      html: `<a href="http://localhost:${config.port}/auth/verify/${token}">Verify email</a>`,
move host localhost to config

2020-10-08 15:01 UTC, odykyi requested changes
comments

2020-10-08 16:34 UTC, LesyaTkachuk commented on src/helpers/nodmailer.js
> +      html: `<a href="http://localhost:${config.port}/auth/verify/${token}">Verify email</a>`,
добавила host в config

2020-10-12 09:00 UTC, odykyi approved these changes

2020-10-12 09:00 UTC, merged